name: Doxa API CI

on: push
jobs:
  unit-tests:
    name: API Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Unit tests with jest
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
      - name: validate serverless yml
        uses: serverless/github-action@v2.18.0
        with:
          args: -c "serverless deploy --noDeploy --stage=dev --verbose"
          entrypoint: /bin/sh
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Unit tests with jest
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Deploy
        uses: serverless/github-action@v2.18.0
        with:
          args: -c "serverless deploy --stage=dev --verbose"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: 1
